# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-26 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lLame',
            new_name='lName',
        ),
    ]
